// https://www.reddit.com/r/sfwpornnetwork/wiki/network

export const allsubs = [
  {
    category: "Nature",
    subs: [
      "EarthPorn",
      "BotanicalPorn",
      "WaterPorn",
      "SeaPorn",
      "SkyPorn",
      "FirePorn",
      "DesertPorn",
      "WinterPorn",
      "AutumnPorn",
      "WeatherPorn",
      "GeologyPorn",
      "SpacePorn",
      "BeachPorn",
      "MushroomPorn",
      "SpringPorn",
      "SummerPorn",
      "LavaPorn",
      "LakePorn",
    ],
  },
  {
    category: "Synthetic",
    subs: [
      "CityPorn",
      "VillagePorn",
      "RuralPorn",
      "ArchitecturePorn",
      "HousePorn",
      "CabinPorn",
      "ChurchPorn",
      "AbandonedPorn",
      "CemeteryPorn",
      "InfrastructurePorn",
      "MachinePorn",
      "CarPorn",
      "F1Porn",
      "MotorcyclePorn",
      "MilitaryPorn",
      "GunPorn",
      "KnifePorn",
      "BoatPorn",
      "RidesPorn",
      "DestructionPorn",
      "ThingsCutInHalfPorn",
      "StarshipPorn",
      "ToolPorn",
      "TechnologyPorn",
      "BridgePorn",
      "PolicePorn",
      "SteamPorn",
      "RetailPorn",
      "SpaceFlightPorn",
      "roadporn",
      "drydockporn",
    ],
  },
  {
    category: "Organic",
    subs: [
      "AnimalPorn",
      "HumanPorn",
      "EarthlingPorn",
      "AdrenalinePorn",
      "ClimbingPorn",
      "SportsPorn",
      "AgriculturePorn",
      "TeaPorn",
      "BonsaiPorn",
      "FoodPorn",
      "CulinaryPorn",
      "DessertPorn",
    ],
  },
  {
    category: "Aesthetic",
    subs: [
      "DesignPorn",
      "RoomPorn",
      "AlbumArtPorn",
      "MetalPorn",
      "MoviePosterPorn",
      "TelevisionPosterPorn",
      "ComicBookPorn",
      "StreetArtPorn",
      "AdPorn",
      "ArtPorn",
      "FractalPorn",
      "InstrumentPorn",
      "ExposurePorn",
      "MacroPorn",
      "MicroPorn",
      "GeekPorn",
      "MTGPorn",
      "GamerPorn",
      "PowerWashingPorn",
      "AerialPorn",
      "OrganizationPorn",
      "FashionPorn",
      "AVPorn",
      "ApocalypsePorn",
      "InfraredPorn",
      "ViewPorn",
      "HellscapePorn",
      "sculptureporn",
    ],
  },
  {
    category: "Scholastic",
    subs: [
      "HistoryPorn",
      "UniformPorn",
      "BookPorn",
      "NewsPorn",
      "QuotesPorn",
      "FuturePorn",
      "FossilPorn",
      "MegalithPorn",
      "ArtefactPorn",
    ],
  },
];
